### ISSUE TITLE
Failed to build libquickjs on Windows

### ISSUE THREAD

**Issue by GalAster** [xu-cheng/katex-rs#1]
```log
   Compiling libquickjs-sys v0.4.0
error: failed to run custom build command for `libquickjs-sys v0.4.0`

Caused by:
  process didn't exit successfully: `D:\Rust\katex-rs\target\debug\build\libquickjs-sys-41555e9664b161d9\build-script-build` (exit code: 101)
--- stderr
Applying patches...
Applying "js-tobigint64-overflow.patch"...
thread 'main' panicked at 'Could not apply patches: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\Aster\.cargo\registry\src\github.com-1ecc6299db9ec823\libquickjs-sys-0.4.0\build.rs:100:22
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\io\mod.rs:1428
   5: std::sys_common::backtrace::_print
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:378
  11: core::panicking::panic_fmt
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libcore\panicking.rs:85
  12: core::option::expect_none_failed
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libcore\option.rs:1211
  13: core::result::Result<std::process::Child, std::io::error::Error>::expect<std::process::Child,std::io::error::Error>
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\src\libcore\result.rs:961
  14: build_script_build::apply_patches
             at .\build.rs:100
  15: build_script_build::main
             at .\build.rs:70
  16: std::rt::lang_start::{{closure}}<()>
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\src\libstd\rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\rt.rs:52
  18: std::panicking::try::do_call<closure-0,i32>
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:303
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libpanic_unwind\lib.rs:86
  20: std::panicking::try
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\panic.rs:394
  22: std::rt::lang_start_internal
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\/src\libstd\rt.rs:51
  23: std::rt::lang_start<()>
             at /rustc/433aae93e4ef866a1fdfefad136b32ed89acd3e7\src\libstd\rt.rs:67
  24: main
  25: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


Process finished with exit code 101

```

**Comment by xu-cheng** [comment]
This is an upstream issue. See https://github.com/theduke/quickjs-rs/issues/18 for details. 

It is possible to build quickjs in `x86_64-pc-windows-gnu` target through cross-compilation with the following patch https://github.com/theduke/quickjs-rs/pull/57

**Comment by krisradio** [comment]
Update on this bug since [quickjs-rs#57](https://github.com/theduke/quickjs-rs/pull/57) was merged?

**Comment by xu-cheng** [comment]
@krisradio, you need to wait quickjs-rs to upload a new release to crates.io. After which, it should be possible to build this library in `x86_64-pc-windows-gnu` target through cross-compilation.

**Comment by krisradio** [comment]
@xu-cheng awesome, thank you!

**Comment by xu-cheng** [comment]
Close this issue for now as it is fixed in upstream.

To build for Windows target using cross-complication, you can do the following on Ubuntu: 
```
sudo apt-get install mingw-w64 -y
cargo build --target x86_64-pc-windows-gnu
```

See https://github.com/xu-cheng/pandoc-katex for a complete example.

You should be able to do the similar things on Windows using MSYS2/MingGW.
